// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SpeedyBoiAchievements
{
        public const string achievement_longstrider_x100 = "CgkI1ez-l5oDEAIQAQ"; // <GPGSID>
        public const string achievement_longstrider_x10000 = "CgkI1ez-l5oDEAIQAw"; // <GPGSID>
        public const string achievement_badge_of_honour = "CgkI1ez-l5oDEAIQBA"; // <GPGSID>
        public const string achievement_baby_steps = "CgkI1ez-l5oDEAIQAA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI1ez-l5oDEAIQBg"; // <GPGSID>
        public const string achievement_longstrider_x1000 = "CgkI1ez-l5oDEAIQAg"; // <GPGSID>

}

